include: package:code_secure_flutter/analysis_options_1.0.0.yaml

analyzer:
  plugins:
    - custom_lint
    
custom_lint:
  rules:
    - avoid_long_and_complex_functions:
      error_severity: Warning
      function_max_char_count: 1100
    - avoid_nesting:
      error_severity: Warning
      nesting_max_depth: 2
    - require_parameter_assert:
      error_severity: Warning
      exclude_parameter_types: 
        - TestType
        - TestType?
    - avoid_recursion: 
      error_severity: Warning
    - check_return_value: 
      error_severity: Warning
    - loops_require_fixed_bound: 
      error_severity: Warning
